# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "{build}"

image:
- Visual Studio 2015

environment:
  global:
    VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    MRUBY_CLI_LOCAL: 1
    TOOLCHAIN: gcc
  matrix:
  - MRUBY_VERSION: 1.3.0
    COMPILER: C:\MinGW
  - MRUBY_VERSION: head
    COMPILER: C:\MinGW

matrix:
  allow_failures:
  - MRUBY_VERSION: head

init:
- CALL "%VCVARSALL%" amd64
- SET PATH=%COMPILER%\bin;%PATH%
- SET PATH=C:\Ruby23-x64\bin;%PATH%
- SET PATH=C:\cygwin\bin;%PATH%
- gcc --version

build_script:
- rake compile

test_script:
- DEL mruby\mrbgems\mruby-compiler\bintest\*.rb
- rake test:bintest
